#![allow(unreachable_pub)]

xflags::xflags! {
    src "./src/flags.rs"
    /// Run custom build command.
    cmd xtask {
        default cmd help {
            /// Print help information.
            optional -h,--help
        }
        /// 编译着色器
        cmd shader {
            /// 可选的是否编译所有类型，默认是所有
            optional -a,--gen-all
        }
    }
}
// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Help(Help),
    Shader(Shader),
}

#[derive(Debug)]
pub struct Help {
    pub help: bool,
}

#[derive(Debug)]
pub struct Shader {
    pub gen_all: bool,
}

impl Xtask {
    pub const HELP: &'static str = Self::HELP_;

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
